# Generated by Django 3.1.3 on 2020-12-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssm_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
