# Generated by Django 3.1.3 on 2020-11-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_socket_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='loginprofile',
            name='email',
            field=models.EmailField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
