# Generated by Django 3.1.3 on 2020-11-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_socket_app', '0003_registerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerprofile',
            name='first_name',
            field=models.TextField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerprofile',
            name='last_name',
            field=models.TextField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
