# Generated by Django 3.1.3 on 2020-11-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_socket_app', '0005_registerprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginprofile',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='registerprofile',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='registerprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
