# Generated by Django 3.1.3 on 2020-11-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_socket_app', '0006_auto_20201129_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterProfile',
        ),
    ]
