# Generated by Django 3.1.3 on 2020-11-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_socket_app', '0007_delete_registerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogInProfile',
        ),
    ]
