# Generated by Django 3.1.3 on 2020-12-03 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_socket_app', '0010_auto_20201202_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartsocket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartsocket',
            name='owner',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smartsocket',
            name='unique_address',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
