# Generated by Django 3.1.3 on 2020-12-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssm_auth', '0002_auto_20201202_1927'),
        ('smart_socket_app', '0011_auto_20201203_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartsocket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ssm_auth.userprofile'),
            preserve_default=False,
        ),
    ]
