# Generated by Django 3.1.3 on 2020-12-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_socket_app', '0012_smartsocket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartsocket',
            name='user',
        ),
    ]
